name: "Release"

on:
  push:
    branches:
      - main
      - beta
      - beta-**

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: checkout
        uses: actions/checkout@v2.4.2
      - name: node
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
      - name: install react
        run: npm i react
      - name: install dependencies
        run: npm ci
      - name: build
        run: npm run build
      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish
